//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToursSitePreBata.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TourPhotoMapping
    {
        public int ID { get; set; }
        public int ImageNumber { get; set; }
        public int TourID { get; set; }
        public int TourPhotoID { get; set; }
    
        public virtual tourPhoto tourPhoto { get; set; }
        public virtual Tour Tour { get; set; }
    }
}
