//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToursSitePreBata.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ToursDBEntities : DbContext
    {
        public ToursDBEntities()
            : base("name=ToursDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tourCategory> tourCategories { get; set; }
        public virtual DbSet<tourClass> tourClasses { get; set; }
        public virtual DbSet<tourGallery> tourGalleries { get; set; }
        public virtual DbSet<tourPhoto> tourPhotoes { get; set; }
        public virtual DbSet<Tour> Tours { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
